name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Clone GitHub repository
      uses: actions/checkout@v2
    - name: Download and extract AutoHotKey
      run: |
        powershell.exe curl https://autohotkey.com/download/ahk.zip -o ahk.zip
        powershell.exe Expand-Archive -Path ahk.zip -DestinationPath .\AutoHotKey\ -Verbose
        powershell.exe ls
        powershell.exe ls .\AutoHotKey
        powershell.exe ls .\AutoHotKey\Compiler
    - name: Run AutoHotKey compiler to generate binary
      run:  .\AutoHotKey\Compiler\Ahk2Exe.exe /in LiveEnhancementSuite.ahk /out "Live Enhancement Suite.exe" /icon resources\blueico.ico
    - name: Install Inno Setup 6.0.4 for Installer Creation
      run: |
        powershell.exe ls
        powershell.exe ls .\AutoHotKey
        powershell.exe ls .\AutoHotKey\Compiler
        powershell.exe curl http://files.jrsoftware.org/is/6/innosetup-6.0.4.exe -o innosetup-6.0.4.exe
        ./innosetup-6.0.4.exe /VERYSILENT /SUPPRESSMSGBOXES
    - name: Run Inno Setup script and generate checksums
      run: |
        $InnoSetupCmdLocation="C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
        & $InnoSetupCmdLocation /q innoSetupScript.iss
        CertUtil -hashfile .\Output\LiveEnhancementSuiteSetup-x64.exe SHA256 | Select -SkipLast 1 >> chksm
        (Get-Content chksm) -join ' ' >> .\Output\CHECKSUM.txt
        Compress-Archive -LiteralPath .\Output\LiveEnhancementSuiteSetup-x64.exe, .\Output\CHECKSUM.txt -DestinationPath .\LiveEnhancementSuiteSetup-x64.zip
        Remove-Item chksm
        CertUtil -hashfile "Live Enhancement Suite.exe" SHA256 | Select -SkipLast 1 >> chksm
        (Get-Content chksm) -join ' ' >> CHECKSUM.txt
        Compress-Archive -LiteralPath "Live Enhancement Suite.exe", CHECKSUM.txt -DestinationPath .\LiveEnhancementSuitePortable-x64.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .\LiveEnhancementSuiteSetup-x64.zip
        asset_name: LiveEnhancementSuiteSetup-x64.zip
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload portable version to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .\LiveEnhancementSuitePortable-x64.zip
        asset_name: LiveEnhancementSuitePortable-x64.zip
        tag: ${{ github.ref }}
        overwrite: true
  
